import { Syne } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";

const syne = Syne({
  weight: ["400", "500", "700"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${syne.className} `}>
        <Header />
        <div className="">{children}</div>
      </body>
    </html>
  );
}
